- tasks/bash.sh
- tasks/ruby.rb
Extend bash implementation by adding default location of facter to the path.
Extend ruby implementation to handle the case where puppet-agent is not installed in default location.
> (BOLT-688) Expand search for facter task

- CHANGELOG.md
- Gemfile
- metadata.json
Shipping modules currently requires setting PUPPET_GEM_VERSION to a
Puppet 5 release. Running specs requires Puppet 6.0.0, so pin that
unless otherwise specified.
> Read PUPPET_GEM_VERSION

- .travis.yml
- CHANGELOG.md
- Gemfile
- README.md
- Rakefile
- spec/.fixtures.yml
- spec/acceptance/init_spec.rb
- spec/plans/init_spec.rb
- spec/spec_helper_acceptance.rb
- tasks/bash.sh
The puppetlabs-puppet_agent install_shell.sh implementation relies on determining target platform and version. With the introduction of multi-file task support this commit facilitates the use of the facts::bash implementation. The bash.sh implementation can now accept a positional argument that can be set to `platform` or `version`. This results in the requested data being printed to stdout instead of the full JSON report that would be printed without the positional argument.
> (BOLT-915) Make bash.sh facts implementation shareable

- .fixtures.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- metadata.json
Only require Bolt when the GEM_BOLT environment variable is set to avoid conflicts with puppet5 in the publish to Forge Jenkins job.
> (BOLT-915) Publish 0.4.1 to Forge

- spec/acceptance/init_spec.rb
The acceptance test to verify bash.sh can accept a positional argument should not be run against windows targets.
> (BOLT-915) Do not run bash.sh against windows targets

- Gemfile
- spec/acceptance/init_spec.rb
- spec/acceptance/linux_spec.rb
- spec/acceptance/windows_spec.rb
- tasks/bash.sh
- tasks/ruby.rb
When `lsb_release` is used to find platform name in the bash implementation for some red-hat versions (example redhat-5-x86_64) the OS name fact reports `RedHatEnterpriseServer`. This commit changes shortens the output to `RedHat` as the puppet_agent::install task expects.
When a target is missing both `lsb_release` and `os-release` pick up the name and version from `redhat-release`.
> (BOLT-997) Clean bash implementation for RedHat

- spec/acceptance/init_spec.rb
- spec/acceptance/linux_spec.rb
- spec/acceptance/windows_spec.rb
Previously, the tests were omitting the `params` argument to `run_task`.
In newer versions of BoltSpec, that parameter is going to be required,
so now we always pass it.
> (BOLT-1057) Pass required args to run_task

- spec/acceptance/init_spec.rb
- spec/acceptance/linux_spec.rb
- spec/acceptance/windows_spec.rb
- spec/spec_helper_acceptance.rb
All of the acceptance tests for the bolt task/plan content is shared by tests. Move to spec_helper_acceptance.
> (MODULES-8717) Move shared dependency to spec_helper

- .sync.yml
- Gemfile
- spec/acceptance/init_spec.rb
- spec/acceptance/linux_spec.rb
- spec/acceptance/windows_spec.rb
- tasks/bash.sh
- tasks/powershell.ps1
As pointed out in https://github.com/puppetlabs/puppetlabs-facts/issues/24 there is a typo in the bash facts implementation that can result in failure when reading `/usr/lib/os-release`. This commit fixes the typo.
> (MODULES-8750) Improve facts bash task implementation

- .gitattributes
Prior to this commit there was no gitattributes file so all files will, by default, check out on Windows as CRLF. This causes problems when executing the tasks against *nix nodes, particularly shell script tasks, as the carriage return is included in the copied file.
This commit adds a gitattribute file which normalizes files which should not have CRLF to LF. This set of file types to have LF ensured was taken from the provision and scheduled_task modules, both of which use this same list. The puppet_agent module uses a similar though smaller list.
> (FM-7967) Ensure bash script EOL is LF

- CHANGELOG.md
- metadata.json
- spec/acceptance/linux_spec.rb
- tasks/bash.sh
Previously the codename was at the top level as `os` for the bash implementation. This commit pushes it down under `distro` to mirrow what the C++ facter implementation does.
> (MODULES-9530) Mirror C++ facter structure for codename

- .travis.yml
- CODEOWNERS
- spec/plans/init_spec.rb
This addresses an issue with Travis and bundler that causes
rubygems-update to fail.
It also updates expected output in tests to account for Bolt outputting
`target` instead of `node`.
Lastly, this adds the bolt team as codeowners.
> (maint) Update broken tests and add CODEOWNERS file

- CHANGELOG.md
- tasks/bash.sh
This fixes a bug where facts were not sourced correctly from
`/etc/os-release` or `/usr/lib/os-release` on systemd platforms when
using bash 3.1 or 3.2. Previously, the `os-release` file was sourced
by using process substitution, which is incompatible with some versions
of bash. This updates the script to source from `/dev/stdin` instead.
> Source facts for systemd platforms using bash 3.1 and 3.2

- CHANGELOG.md
- tasks/bash.sh
This updates the `facts` task to properly return a platform's version
when it falls back to using `uname` to determine the platform name and
version. Previously, whenever the task fell back to using `uname`, it
would return an empty string for the version.
Fixes #34
> (GH-34) Return version when using `uname`

- tasks/bash.sh
- tasks/powershell.ps1
This restores the behavior that was removed in 9b7fe39, whereby the
shell and powershell implementations of the facts task will detect
whether `facter` is available and call out to it if possible.
This was removed because it leads to a situation where you can get
different kinds of output from the same implementation of the task
depending on where it's being run. But since the unit of abstraction is
the task itself, and not an implementation, it's better to provide the
full `facter` output in as many cases as possible, without the user
having to explicitly mark the target as having the `puppet-agent`
feature first. This makes the output less consistent between targets for
the same implementation, but more consistent for the same target between
implementations.
> Delegate to facter if installed

- CHANGELOG.md
- README.md
- plans/info.pp
- plans/init.pp
- spec/plans/info_spec.rb
- spec/plans/init_spec.rb
This changes the `$nodes` parameters in both the `facts` and
`facts::info` plans to `$targets` as part of a larger update to Bolt's
bundled content.
Part of https://github.com/puppetlabs/bolt/issues/1376
> (GH-1376) Change $nodes param to $targets in plans

- .fixtures.yml
- tasks/init.json
- tasks/ruby.rb
We rely on the puppet-agent being installed for targets that have the
`pupet-agent` feature. However we assign `puppet-agent` to localhost
expecting it will use Bolt's puppet-agent, which means puppet resources
aren't at the expected `/opt/puppetlabs/puppet` path. This will now look
for facter packaged with Puppet first, then packaged with
Bolt, then lastly will just call `facter` to see if it's elsewhere on
the PATH.
This also makes a number of modifications to how the executable string
is munged and called on Windows, so that the task is runnable on that
platform. It also uses the ruby_task_helper module in order to catch and
display errors.
> (bug-fix) Use RbConfig.ruby instead of hardcoded path

- plans/external.pp
This adds the prototype for a plan that takes the absolute path to a
directory containing external facts scripts. It runs each script and
munges the output to a Hash, then adds the facts to the Bolt Target
objects and returns the targets. This is useful for gathering
information from remote systems without relying on facter or a bash
script, and allows users to easily create their own facts and handle
them in Bolt plans.
Relates to https://github.com/puppetlabs/bolt/issues/1981
> (PROTOTYPE)(GH-1981) Add external facts plan

- plans/info.pp
- plans/init.pp
This commit updates the puppet-strings docs for plan parameters so that CLI and console can print metadata.
> (GH-42) Format plan metadata for plan parameters

- tasks/ruby.rb
Before this change, the facts task would assume that if #{rubydir}/facter exists, this should be the executable for facter.
On Puppet Agent 6 this file exists and is the entry point for linux. The entry point for windows on Puppet 6 that ships with cFacter is  #{rubydir}/facter.exe .
Open 3 knows how to execute files on Windows without explicitly specifying the extensions, eg:
```
irb(main):006:0> stdout, stderr, status = Open3.capture3("C:\\Program Files\\Puppet Labs\\Puppet\\puppet\\bin\\ruby.exe", "-v")
irb(main):007:0> stdout, stderr, status = Open3.capture3("C:\\Program Files\\Puppet Labs\\Puppet\\puppet\\bin\\ruby", "-v")
```
On Puppet Agent 7, we ship Facter 4 that is written in ruby, so facter.exe executable no longer exists. Because of this:
_C:\\Program Files\\Puppet …
> (IAC-1127) search for facter.exe on Windows platforms

- tasks/ruby.rb
Prior to this commit, when facter would throw up errors we
would just eat them and not give any context as to why
facter gave an exit code of 1.
After this commit, we surface errors from facter in the
task result.
> Bubble up errors from facter if any

- tasks/ruby.rb
This fixes issue: https://github.com/puppetlabs/bolt/issues/2344
The puppetlabs-facts module should use the bat files preferably as the environment setup that is done in the bat file is needed for facter to avoid the ruby errors. 
Testing run with this fix available here: https://github.com/puppetlabs/puppetlabs-iis/actions/runs/383224064
> Use bat files if possible

- CHANGELOG.md
- metadata.json
- tasks/init.json
- tasks/powershell.json
- tasks/ruby.json
Explicitly require the task helper for the task that uses it and do not explicitly use `both` as the input method as it is the default.
> (maint) Clean up task metadata

- tasks/bash.sh
FreeBSD does not match the default capitalization rule (Freebsd).
> (maint) Adjust FreeBSD capitalization

- CHANGELOG.md
- metadata.json
Release the updated OS fact with correct casing for FreeBSD.
> (maint) Prep for 1.5.0 release
